title: Dimas Bagus Setiawan
description: >-
  Professional profile and CV of Dimas Bagus Setiawan, Process Quality Engineer.
baseurl: ""
url: "https://yourusername.github.io" # Replace with your GitHub username
theme: minima
plugins:
  - jekyll-feed
